name: MinGW Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      uses: Denzy7/action-mingw@v0.1

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"

    - name: Build project
      run: |
        make
