name: MinGW Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: cmake gcc-g++

    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles"

    - name: Build project
      run: |
        cd build
        mingw32-make
